import os
import smtplib
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

# Initialize Environment
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("EmailManager")

def send_purchase_order_email(file_path, recipient_email=None):
    """
    Sends a Purchase Order CSV as an email attachment.
    Uses SMTP credentials from environment variables.
    """
    # 1. Configuration from Environment
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", 587))
    smtp_user = os.getenv("SMTP_USER")
    smtp_pass = os.getenv("SMTP_PASS")
    
    # Recipient: Use provided email or fallback to default supplier email
    to_email = recipient_email or os.getenv("SUPPLIER_EMAIL")

    if not all([smtp_user, smtp_pass, to_email]):
        logger.warning("Email credentials or recipient missing. Skipping email dispatch.")
        return False

    if not os.path.exists(file_path):
        logger.error(f"PO File not found for email dispatch: {file_path}")
        return False

    try:
        # 2. Create Message
        msg = MIMEMultipart()
        msg['From'] = smtp_user
        msg['To'] = to_email
        msg['Subject'] = f"MediStock AI: New Purchase Order - {os.path.basename(file_path)}"

        body = "Please find the attached Purchase Order generated by the MediStock AI Inventory System."
        msg.attach(MIMEText(body, 'plain'))

        # 3. Attach CSV File
        with open(file_path, "rb") as attachment:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(attachment.read())
            encoders.encode_base64(part)
            part.add_header(
                'Content-Disposition',
                f'attachment; filename={os.path.basename(file_path)}'
            )
            msg.attach(part)

        # 4. Connect and Send
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls() # Secure connection
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
            
        logger.info(f"SUCCESS: Purchase Order email sent to {to_email}")
        return True

    except Exception as e:
        logger.error(f"FAILURE: Could not send PO email. Error: {str(e)}")
        return False
